### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by pdedumast**

### CODE REVIEW

**Comment by t-sanchez** [comment]
Hey @sebastientourbier, 
I talked with @pdedumast and we're not sure if you need to do something manual for the `deploy_docker_latest` step to pass. If it is the case, could you get in touch to tell us what needs to be done?

Feel free to drop me an email at my unil address if it's simpler. 

Cheers,
Thomas

**Comment by t-sanchez** [comment]
Hey @sebastientourbier 

Any update on the deploy_docker_latest?

Feel free to drop me an email at my unil address or reply here.

Cheers,
Thomas

**Comment by sebastientourbier** [comment]
Dear @pdedumast  and @t-sanchez,
Hope you are doing well!
I can see you are working hard those days on MIALSRTK, this is really great :) !
Would you be available for a meeting next week to follow up?
If yes please could you suggest me different slots?

**Review by t-sanchez — APPROVED** [review]
Longstanding work, let's release the v2.1.0!

**Comment by sebastientourbier** [comment]
I am sorry to let you know but we are a community and this should not have been self-reviewed and the merge forced when codacy is not happy. Hope this would not happen in the future 🙏

**Comment by sebastientourbier** [comment]
Also @t-sanchez , please use our conventional commits, i.e `FIX:`, `ENH:`, ... as described in the contributing doc: https://mialsrtk.readthedocs.io/en/latest/contributing.html#get-started.

**Comment by sebastientourbier** [comment]
Anyway 👏 👏 👏 🚀 🚀 🚀

**Pull request merged**
