### PR TITLE
Fix: Review motion index computation and add a note

### PR DESCRIPTION
**Pull request by sebastientourbier**
This PR is dedicated to address #80 reporting a problem with motion index computation.
It includes:
* the addition of a note in the docstring of the `StacksOrdering` interface 
https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/a2f9244111b7caaeb0d51049e05dd94829143755/pymialsrtk/interfaces/preprocess.py#L963-L972
* a new implementation that excludes the centroids of the problematic slices from the motion index computation
   ```python
      centroid_coord = np.zeros((data.shape[2], 2))

      for i in range(data.shape[2]):
          moments = skimage.measure.moments(data[..., i])

          try:
              centroid_coordx = moments[0, 1] / moments[0, 0]
              centroid_coordy = moments[1, 0] / moments[0, 0]
          # This happens in the case of discontinuous brain masks
          except ZeroDivisionError:
              centroid_coordx = np.nan
              centroid_coordy = np.nan

          centroid_coord[i, :] = [centroid_coordx, centroid_coordy]

      centroid_coord = centroid_coord[~np.isnan(centroid_coord)]
      centroid_coord = np.reshape(centroid_coord, (int(centroid_coord.shape[0] / 2), 2))

      nb_slices = centroid_coord.shape[0]
      score = (np.var(centroid_coord[:, 0]) + np.var(centroid_coord[:, 1])) / nb_slices
  ```

### CODE REVIEW

**Comment by sebastientourbier** [comment]
https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/a2f9244111b7caaeb0d51049e05dd94829143755/pymialsrtk/interfaces/preprocess.py#L1018-L1037
@helenelajous @pdedumast Does it make sense ?

**Comment by helenelajous** [comment]
Yes, I think the computation of the motion index is more realistic this way - thank you!
A second step would be to return the number of NaN/rejected slices to account for motion-related intensity artifacts like signal dropouts and use it to penalize this stack in the optional stack_ordering interface.

**Review by helenelajous — COMMENTED** [review]
The bias introduced in the computation of the motion index by setting the centroid coordinates to 0 before 'v2.0.2' is well explained.
What about using the information provided by the number of NaN/rejected slices to penalize a stack in the optional stack_ordering interface taking into account motion-related intensity artifacts like signal dropouts?

**Comment by sebastientourbier** [comment]
> What about using the information provided by the number of NaN/rejected slices to penalize a stack in the optional stack_ordering interface taking into account motion-related intensity artifacts like signal dropouts?

@helenelajous I agree it would be a nice addon. What about we keep this PR dedicated to better inform about the implementation and fix it with the nan value and we open a new issue related to this new feature?

**Review by helenelajous — APPROVED** [review]

**Comment by sebastientourbier** [comment]
@all-contributors please add @helenelajous and @pdedumast for review

**Pull request merged**
