### PR TITLE
REL: MIALSRTK v2.1.0

### PR DESCRIPTION
**Pull request by sebastientourbier**
This PR is dedicated to finalize v2.1.0 release.

### CODE REVIEW

**Comment by sebastientourbier** [comment]
@t-sanchez Once all tests are green and you review and approve this PR, I will merge it into the master and make the release 😄

**Review by t-sanchez — APPROVED** [review]
Hi @sebastientourbier, I went through the files and through the documentation, everything seems in order to me.

**Comment by t-sanchez** [comment]
Codacy seems to be stuck however.

**Comment by sebastientourbier** [comment]
Yes trying to relaunch an analysis directly from codacy to see if this updates the state here

**Comment by sebastientourbier** [comment]
Thanks a lot @t-sanchez for the review!

**Pull request merged**
