### PR TITLE
MIALSRK v2.0.2

### PR DESCRIPTION
**Pull request by sebastientourbier**
PR dedicated to the developement of the upcoming v2.0.2 release.

### CODE REVIEW

**Review by pdedumast — APPROVED** [review]

**Comment by sebastientourbier** [comment]
@all-contributors please add @helenelajous for bug and test

**Review by pdedumast — APPROVED** [review]

**Comment by sebastientourbier** [comment]
@pdedumast @hamzake This PR for the upcoming version has already integrated a large number of changes and I would like to make a release before we integrate the reorientation of scans to standard template space. I should still take care of the following few last things before the release:
- [ ] Create a new singularity token for publication of the singularity container image during version release in circleci
- [ ] Update `documentation/changes.rst`
- [ ] Update documentation with details about the report

**Comment by pdedumast** [comment]
@sebastientourbier, building commit [6ff0b56](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/pull/70/commits/6ff0b569dc938568b24eb986282f1a9a7a3cc486) locally, I'm running into errors that do not seem to happen in the tests... 
Though I cannot run the process. The error (`AttributeError: 'DynamicTraitedSpec' object has no attribute 'report_image'`) seems to be be caused by the last steps of the pipeline with the data sinker.

**Comment by sebastientourbier** [comment]
@all-contributors please add pahagman as a contributor for data and fundingFinding

**Review by pdedumast — APPROVED** [review]

**Pull request merged**
