### PR TITLE
[ENH] Add possibility for the user to custom the skipped interfaces

### PR DESCRIPTION
**Pull request by pdedumast**

### CODE REVIEW

**Comment by sebastientourbier** [comment]
@pdedumast If needed I activated the generation of the doc for this branch. I can be viewed at https://mialsrtk.readthedocs.io/en/27_custom_skipped_interfaces/

**Review by sebastientourbier — APPROVED** [review]
Seems ready to be merged ! 
Great job @pdedumast !
For the future, we should have in mind to set  `skip_stacks_ordering` to `false` in the configuration file (we could also make two different configuration files) otherwise this decreases code coverage.

**Comment by pdedumast** [comment]
> For the future, we should have in mind to set `skip_stacks_ordering` to `false` in the configuration file (we could also make two different configuration files) otherwise this decreases code coverage.

@sebastientourbier Indeed, `skip_stacks_ordering=False` is the default value. 
I did not mean to commit the json parameter file, this is a mistake. Though, as how it is implemented now, the list of output files will not be modified when switching `skip_stacks_ordering` on and off.

**Comment by pdedumast** [comment]
@sebastientourbier  seems that old required tests are blocking the possibility to merge. Any idea?

**Comment by sebastientourbier** [comment]
> 
> 
> @sebastientourbier seems that old required tests are blocking the possibility to merge. Any idea?

Yes, for the moment I need to force the merge. That's what I did ;)

**Pull request merged**
