### PR TITLE
Integration of automatic DL-based brain extraction

### PR DESCRIPTION
**Pull request by sebastientourbier**
This PR is dedicated to the integration of automatic DL-based brain extraction module developed by @hamzake  into the upcoming v.2.0 version (PR #2).

Tasks:
- [x] Implementation of python executable for DL-based brain extraction 
- [x] Implementation of Nipype interface with example in a notebook
- [x] Update branch with most recent version of  v2.0 branch (dev-pdg-hk)
- [x] Copy code for the nipype interface in pymialsrtk/interfaces/preprocess.py 
- [x] Update BIDS App parser with boolean flag ``--manual`` and include the brain extraction interface in the BIDS workflow within a ``ìf... else`` block, 
- [x] Test BIDS App locally on the sample dataset with manual masks 
- [x] Update command in circleci with boolean flag ``--manual`` 
- [x] Update list of test outputs to make test passed on circleci
- [x] Update version in ``pymialsrtk/info.py``
- [x] Create software documentation on readthedocs: https://mialsrtk.readthedocs.io/en/dev-pgd-hk/
- [x] Update brain extraction with two phases framework
- [x] Test BIDS App locally on the sample dataset with automatic brain extraction
- [x] Add test in ``.circleci/config.yml`` with automatic brain extraction
- Integrate coverage review in circleci:
  - [x] Install pycoverage inside the docker image 
  - [x] Update call to bids-app run with coverage (``Dockerfile`` and ``run.py``) 
  - [x] Update command of test in ``.circleci/config.yml`` 
- [x] Improve code quality based on codacy report: https://app.codacy.com/gh/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/pullRequest?prid=6104928
- Update doc: 
  - [x] Check parser is properly updated on readthedocs: https://mialsrtk.readthedocs.io/en/dev-hk/
  - [x] Update ``documentation/outputs.rst``

### CODE REVIEW

**Comment by sebastientourbier** [comment]
@hamzake Perfect!

**Comment by sebastientourbier** [comment]
@hamzake If you want to commit any new change to branch dev-hk, **please pull first the latest version from GitHub** as I merged changes we made to make the BIDS App.

**Comment by hamzake** [comment]
> @hamzake If you want to commit any new change to branch dev-hk, **please pull first the latest version from GitHub** as I merged changes we made to make the BIDS App (more details @ PR #15).

Done!

**Comment by sebastientourbier** [comment]
@hamzake Just to tell you I am taking some time now to integrate your interface in the workflow of the BIDS App. Let you know when it is done ;)

**Comment by hamzake** [comment]
> @hamzake Just to tell you I am taking some time now to integrate your interface in the workflow of the BIDS App. Let you know when it is done ;)

Cool thanks!!

**Comment by sebastientourbier** [comment]
@hamzake Everything should be now up-to-date! Everything about the bids-app can be found here:
https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/tree/dev-hk/docker/bidsapp

**Review by sebastientourbier — COMMENTED** [review]
It seems a few unwanted files have been staged to git. This includes in notebooks/ the crash-*.plkz and I am not sure if the the T2w masked should be there if not generated by the brain extraction module.
If this is not the case , *_masked.nii.gz should be moved in derivatives/manual_masks/sub-01/anat and renamed to sub-01_run-XX_desc-brain_T2w.nii.gz to be BIDS compliant.

**Comment by sebastientourbier** [comment]
@hamzake I am currently working on the integration of code quality review and code coverage of the test(s) run on circleci. Let you know when I am done.

**Comment by sebastientourbier** [comment]
@hamzake Just to let know I am done with my changes. In particular:
* Deletion of the crash files in the ``notebooks/`` 
* Integration of code coverage report and code quality review in the continuous integration loop which can be viewed on Codacy (See https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/pull/4#issue-430970170 for link). I also took care of correcting a number of code style errors to make the different linters of the code quality review in codacy happy. 
* There are now two tests on circleCI, one with manual masks, one with automatic brain extraction. Both pipelines run with success 🚀  
* I updated from dev-pgd-hk and added badges for code coverage, code quality grade and latest release in the doc and the readme. I also checked and the doc of the BIDS App inputs has been updated on readthedocs (https://mialsrtk.readthedocs.io/en/dev-hk/usage.html) 

As you can see, all checks (Codacy/Travis/CircleCI/Readthedocs) passed. 
But there is still one more thing before merging: we would need to correct the location where the brain masks are saved at execution of auto brain extraction. 
They should be saved inside the folder of the node dedicated to the brain extraction tasks in the Nipype derivatives directory i.e. ``/output_dir/ipype/sub-01/anatomical_pipeline/rec1/Multiple_Brain_extraction/`` and not in the raw BIDS directory i.e. ``/bids_dir/sub-01/*``. Please could you work on this?

Then we are all good to merge this PR into the main branch of the v2.0.0 release aka dev-pgd-hk 👍

**Review by sebastientourbier — COMMENTED** [review]
@hamzake Just made the few adjustments for the names of the brain masks sinked into `derivatives/pymialsrtk/sub-XX/anat`, checked if the ouputs described in the doc corresponded to the exact outputs and enabled to check the difference of lists of outputs for the two tests on circle CI. 
Seems ready to be merged 🥳

**Pull request merged**
