### PR TITLE
HOTFIX: connection input stacksOrdering

### PR DESCRIPTION
**Pull request by pdedumast**

### CODE REVIEW

**Review by hamzake — APPROVED** [review]

**Review by sebastientourbier — APPROVED** [review]
👍

**Comment by sebastientourbier** [comment]
Seems I should review the rules for test as `deploy_docker_latest`job is only performed by circleci for the master branch but all tests passed and code coverage is about 85%.
Good to merge

**Comment by pdedumast** [comment]
Thanks for merging!

**Comment by sebastientourbier** [comment]
@pdedumast Is it fixing the issue #50 that you reopened and closed?

**Comment by pdedumast** [comment]
Yes, it does!

**Pull request merged**
